# Generated by Django 4.1 on 2025-01-20 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0005_tbl_agriofficer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_notification',
            fields=[
                ('notiid', models.AutoField(primary_key=True, serialize=False)),
                ('notification', models.CharField(max_length=100)),
                ('frdate', models.DateField()),
                ('todate', models.DateField()),
                ('count', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_product')),
            ],
        ),
    ]
