# Generated by Django 4.1 on 2025-01-22 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tbl_agriofficer'),
        ('officerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tbl_notification',
            name='officerid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_agriofficer'),
        ),
    ]
