# Generated by Django 4.1 on 2025-01-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officerapp', '0002_tbl_notification_image_tbl_notification_officerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_service',
            fields=[
                ('serviceid', models.AutoField(primary_key=True, serialize=False)),
                ('servicename', models.CharField(max_length=50)),
            ],
        ),
    ]
