# Generated by Django 4.1 on 2025-02-19 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tbl_agriofficer'),
        ('officerapp', '0003_tbl_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_training',
            fields=[
                ('trainingid', models.AutoField(primary_key=True, serialize=False)),
                ('trainingname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('cdate', models.DateField()),
                ('officerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_agriofficer')),
            ],
        ),
    ]
