# Generated by Django 4.1 on 2025-02-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officerapp', '0004_tbl_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_training',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
