# Generated by Django 4.1 on 2025-02-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officerapp', '0005_tbl_training_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_training',
            name='cdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
