# Generated by Django 4.1 on 2025-02-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officerapp', '0006_alter_tbl_training_cdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_training',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
