# Generated by Django 4.1 on 2025-02-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officerapp', '0007_tbl_training_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_training',
            name='description',
            field=models.CharField(max_length=1050),
        ),
    ]
