from django.urls import path
from officerapp import views
urlpatterns = [
    path('officerindex/', views.officerindex, name='officerindex'),
    path('notification/', views.notification, name='notification'),
    path('noti_process/', views.noti_process, name='noti_process'),
    path('viewnoti/', views.viewnoti, name='viewnoti'),
    path('deletenoti/<notiid>',views.deletenoti,name='deletenoti'),
    path('viewrequest/', views.viewrequest, name='viewrequest'),
    path('requestaccept/<id>', views.requestaccept, name='requestaccept'),
    path('requestreject/<id>', views.requestreject, name='requestreject'),
    path('viewacceptedrejectedpro/', views.viewacceptedrejectedpro, name='viewacceptedrejectedpro'),
    path('service',views.service,name='service'),
    path('service_process',views.service_process,name='service_process'),
    path('viewservice',views.viewservice,name='viewservice'),
    path('deleteservice/<serviceid>',views.deleteservice,name='deleteservice'),
    path('viewinsurance',views.viewinsurance,name='viewinsurance'),
    path('viewmoreinsurance/<applyid>',views.viewmoreinsurance,name='viewmoreinsurance'),
    path('insuranceaccept/<applyid>', views.insuranceaccept, name='remark'),
    path('insurancereject/<applyid>', views.insurancereject, name='insurancereject'),
    path('viewinsuranceapplication', views.viewinsuranceapp, name='viewinsuranceapp'),
    path('viewmoreinsuranceapp/<insid>', views.viewmoreinsuranceapp, name='viewmoreinsuranceapp'),
    path('insuranceappaccept/<insid>', views.insuranceappaccept, name='checkdate'),
    path('insuranceappreject/<insid>', views.insuranceappreject, name='insuranceappreject'),
    path('acceptedinsuranceapp',views.acceptedinsuranceapp,name='acceptedinsuranceapp'),
    path('acceptedinsuranceviewmore/<insid>',views.acceptedinsuranceviewmore,name='acceptedinsuranceviewmore'),
    path('insurancecompletion/<insid>',views.insurancecompletion,name='insurancecompletion'),
    path('addtraining',views.addtraining,name='addtraining'),
    path('viewtariningclass/', views.viewtariningclass, name='viewtariningclass'),
    path('edittraining/<trainingid>', views.edittraining, name='edittraining'),
    path('deletetraining/<trainingid>', views.deletetraining, name='deletetraining'),
    path('viewpayment/', views.viewpayment, name='viewpayment'),
    path('editnoti/<notiid>', views.editnoti, name='editnoti'),
    path('viewprofile', views.viewprofile, name='viewprofile'),
    path('editoffprofile/<officerid>', views.editoffprofile, name='editoffprofile'),

]