# Generated by Django 4.1 on 2025-01-28 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guestapp', '0003_alter_tbl_farmer_regdate'),
        ('officerapp', '0002_tbl_notification_image_tbl_notification_officerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Request',
            fields=[
                ('reqid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('farmerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_farmer')),
                ('notiid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officerapp.tbl_notification')),
            ],
        ),
    ]
