# Generated by Django 4.1 on 2025-01-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_request',
            name='totalamount',
            field=models.IntegerField(default=0),
        ),
    ]
