# Generated by Django 4.1 on 2025-02-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0002_tbl_request_amount_tbl_request_totalamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_request',
            name='amount',
        ),
    ]
