# Generated by Django 4.1 on 2025-02-05 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0003_remove_tbl_request_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_pay',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('totalamount', models.IntegerField()),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('reqid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.tbl_request')),
            ],
        ),
    ]
