# Generated by Django 4.1 on 2025-02-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0004_tbl_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_pay',
            old_name='payment_date',
            new_name='paydate',
        ),
    ]
