# Generated by Django 4.1 on 2025-02-10 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0003_alter_tbl_farmer_regdate'),
        ('farmerapp', '0005_rename_payment_date_tbl_pay_paydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_insurancepolicy',
            fields=[
                ('applyid', models.AutoField(primary_key=True, serialize=False)),
                ('landdetails', models.TextField()),
                ('cropdetails', models.TextField()),
                ('applydate', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=25)),
                ('remarkdate', models.DateField(null=True)),
                ('photo1', models.ImageField(upload_to='')),
                ('photo2', models.ImageField(upload_to='')),
                ('farmerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_farmer')),
            ],
        ),
    ]
