# Generated by Django 4.1 on 2025-02-10 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tbl_agriofficer'),
        ('farmerapp', '0006_tbl_insurancepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_insurancepolicy',
            name='Officerid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_agriofficer'),
        ),
    ]
