# Generated by Django 4.1 on 2025-02-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0007_tbl_insurancepolicy_officerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_insurance',
            fields=[
                ('insuranceid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('photo1', models.ImageField(upload_to='')),
                ('photo2', models.ImageField(upload_to='')),
                ('remarkdate', models.DateField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=50)),
                ('applyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.tbl_insurancepolicy')),
            ],
        ),
    ]
