# Generated by Django 4.1 on 2025-02-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0008_tbl_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_insurance',
            name='type',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
