# Generated by Django 4.1 on 2025-01-23 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tbl_agriofficer'),
        ('guestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_farmer',
            fields=[
                ('farmerid', models.AutoField(primary_key=True, serialize=False)),
                ('farmername', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=25)),
                ('contactno', models.BigIntegerField()),
                ('regdate', models.DateField()),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_login')),
                ('panchayathid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_panchayath')),
            ],
        ),
    ]
