# Generated by Django 4.1 on 2025-01-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0002_tbl_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_farmer',
            name='regdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
